name: CI

on: [push, pull_request]

env:
  ADDITIONAL_DEBS: "clang-tidy libclang-dev"
  CATKIN_LINT: true
  CATKIN_LINT_ARGS: '--strict'
  CMAKE_ARGS: "-DCATKIN_ENABLE_CLANG_TIDY=true"

jobs:
  build:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: noetic, ROS_REPO: testing}
          - {ROS_DISTRO: noetic, ROS_REPO: main}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}

  clang-format:
    name: "Clang-format"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_REPO: testing
          ROS_DISTRO: noetic
          CLANG_FORMAT_CHECK: file
          CLANG_FORMAT_VERSION: 10

  coverage:
    name: "Coverage check"
    strategy:
      matrix:
        package: [pilz_utils]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_REPO: testing
          ROS_DISTRO: noetic
          ADDITIONAL_DEBS: git
          CATKIN_LINT: false
          NOT_TEST_BUILD: true
          PARALLEL_TESTS: false
          AFTER_SCRIPT: 'git clone --depth=1 --branch master https://github.com/PilzDE/industrial_ci_addons.git /industrial_ci_addons && source /industrial_ci_addons/check_coverage.sh && check_coverage ${{ matrix.package }}'
          CMAKE_ARGS: '-DENABLE_COVERAGE_TESTING=ON -DCMAKE_BUILD_TYPE=Debug'
